[package]
name = "atcoder_snippets"
version = "0.0.1"
authors = ["yoshrc"]
edition = "2018"

[dev-dependencies]
criterion = "0.3.1"
rand = "0.7.3"
rand_xorshift = "0.2.0"

[[bench]]
name = "segment_tree"
harness = false

[[bench]]
name = "z"
harness = false
